export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#44474e",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "outline": "#74777f",
        "outline-variant": "#c4c6cf",
        "surface-tint": "#4a5f85",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#011b3e",
        "on-primary-container": "#6f84ad",
        "inverse-primary": "#b2c7f3",
        "secondary": "#0453cd",
        "on-secondary": "#ffffff",
        "secondary-container": "#356ee7",
        "on-secondary-container": "#fefcff",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#0b1c30",
        "on-tertiary-container": "#75859d",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d7e3ff",
        "primary-fixed-dim": "#b2c7f3",
        "on-primary-fixed": "#011b3e",
        "on-primary-fixed-variant": "#32476c",
        "secondary-fixed": "#dae2ff",
        "secondary-fixed-dim": "#b2c5ff",
        "on-secondary-fixed": "#001848",
        "on-secondary-fixed-variant": "#0040a2",
        "tertiary-fixed": "#d3e4fe",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed": "#0b1c30",
        "on-tertiary-fixed-variant": "#38485d",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "margin-page": "40px",
        "gutter-grid": "24px",
        "container-max": "1440px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "base": "8px",
        "section-gap": "4rem",
        "container-padding-desktop": "2.5rem",
        "gutter": "1.5rem",
        "container-padding-mobile": "1.25rem",
        "margin-mobile": "20px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "caption": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "title-lg": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "22px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    }
  }
}
